# Generated by Django 4.0.1 on 2022-01-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlevel',
            name='Level',
        ),
        migrations.RemoveField(
            model_name='userlevel',
            name='user',
        ),
        migrations.AddField(
            model_name='userlevel',
            name='marks',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='userlevel',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='userlevel',
            name='subject',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
